from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from pathlib import Path
import json
import shutil
from typing import Iterable


@dataclass(slots=True)
class DeletionCandidate:
    path: Path
    reason: str
    size_bytes: int


class CleanupManager:
    """Safe cleanup manager with strict path allowlist rules."""

    ALLOWED_SUBDIRS = {"cache", "stripe_wal", "stripe_assembly", "logs", "state", "users"}

    def __init__(self, data_root: Path) -> None:
        self.data_root = data_root.resolve()
        self.state_dir = self.data_root / "state"

    def scan(self, assembly_ttl_days: int = 7) -> list[DeletionCandidate]:
        candidates: list[DeletionCandidate] = []
        if self.state_dir.exists():
            for tmp_file in self.state_dir.glob("*.tmp"):
                size = tmp_file.stat().st_size
                candidates.append(
                    DeletionCandidate(tmp_file, "orphaned_state_tmp", size),
                )
            # Only clean logs generated by RDrive.
            logs_dir = self.data_root / "logs"
            if logs_dir.exists():
                cutoff = datetime.now(UTC) - timedelta(days=14)
                for log_file in logs_dir.glob("*.log"):
                    modified = datetime.fromtimestamp(log_file.stat().st_mtime, tz=UTC)
                    if modified < cutoff:
                        candidates.append(
                            DeletionCandidate(log_file, "old_log_file", log_file.stat().st_size),
                        )

            # Assembly folders can be cleaned after TTL.
            assembly_dir = self.data_root / "stripe_assembly"
            if assembly_dir.exists():
                cutoff = datetime.now(UTC) - timedelta(days=assembly_ttl_days)
                for folder in assembly_dir.iterdir():
                    if not folder.is_dir():
                        continue
                    modified = datetime.fromtimestamp(folder.stat().st_mtime, tz=UTC)
                    if modified < cutoff:
                        candidates.append(
                            DeletionCandidate(folder, "assembly_ttl_expired", self._dir_size(folder)),
                        )

            # Failed/cancelled stripe jobs -> cleanup their WAL dirs.
            jobs_path = self.state_dir / "transfer_jobs.json"
            if jobs_path.exists():
                raw = json.loads(jobs_path.read_text(encoding="utf-8"))
                for job in raw:
                    if job.get("status") not in {"failed", "cancelled"}:
                        continue
                    file_id = str(job.get("file_id", "")).strip()
                    if not file_id:
                        continue
                    wal_path = self.data_root / "stripe_wal" / file_id
                    if wal_path.exists():
                        candidates.append(
                            DeletionCandidate(wal_path, "failed_job_wal", self._dir_size(wal_path)),
                        )
        return candidates

    def execute(self, candidates: Iterable[DeletionCandidate]) -> int:
        freed = 0
        for candidate in candidates:
            self._ensure_safe_path(candidate.path)
            if candidate.path.is_file():
                freed += candidate.size_bytes
                candidate.path.unlink(missing_ok=True)
            elif candidate.path.is_dir():
                freed += self._dir_size(candidate.path)
                shutil.rmtree(candidate.path, ignore_errors=False)
        return freed

    def clean_job(self, file_id: str) -> int:
        total = 0
        for folder_name in ("stripe_wal", "stripe_assembly"):
            path = self.data_root / folder_name / file_id
            if path.exists():
                self._ensure_safe_path(path)
                total += self._dir_size(path)
                shutil.rmtree(path, ignore_errors=False)
        return total

    def _ensure_safe_path(self, path: Path) -> None:
        if path.is_symlink():
            raise PermissionError(f"Refusing to cleanup symlink path: {path}")

        real = path.resolve()
        if not str(real).startswith(str(self.data_root)):
            raise PermissionError(f"Unsafe cleanup path outside RDrive root: {real}")

        rel = real.relative_to(self.data_root)
        if not rel.parts:
            raise PermissionError("Refusing to target RDrive root directly.")

        if rel.parts[0] not in self.ALLOWED_SUBDIRS:
            raise PermissionError(f"Path is outside cleanup allowlist: {real}")

    def _dir_size(self, path: Path) -> int:
        total = 0
        for entry in path.rglob("*"):
            if entry.is_file():
                total += entry.stat().st_size
        return total
